INSERT INTO states_lgas_facilities (state, lgas_facilities) VALUES 
('Akwa Ibom', '{"lgas": [
    {"lga": "Abak", "facilities": ["ak Abak Operational Base Primary Health Centre"]},
    {"lga": "Eastern Obolo", "facilities": ["ak Base Okorette Primary Health Centre"]},
    {"lga": "Eket", "facilities": ["ak Ikot Ebok Primary Health Centre (Operational Base)", "ak Immanuel General Hospital"]},
    {"lga": "Esit Eket", "facilities": ["ak Base Uquo Primary Health Centre", "ak Ebighi Okpono Health Post"]},
    {"lga": "Essien Udim", "facilities": ["ak Afaha Ikot Ebak Primary Health Centre"]},
    {"lga": "Etim Ekpo", "facilities": ["ak Uruk Ata Ikot Ekpor Primary Health Centre (Operational Base)"]},
    {"lga": "Etinan", "facilities": ["ak Etinan Primary Health Centre", "ak Etinan General Hospital"]},
    {"lga": "Ibeno", "facilities": ["ak Primary health center, Ukpenekang", "ak Primary Health Centre, Mkpanak", "ak Ukpenekang Cottage Hospital"]},
    {"lga": "Ibesikpo Asutan", "facilities": ["ak Nung Udoe Primary Health Centre"]},
    {"lga": "Ibiono Ibom", "facilities": ["ak Ikot Akaidem Primary Health Centre", "Primary Health Care Operational Base Ikpa"]},
    {"lga": "Ika", "facilities": ["ak Urua Inyang Primary Health Centre", "Nto Etukudo Health Centre"]},
    {"lga": "Ikono", "facilities": ["ak Ibiaku Primary Health Centre (BASE)", "Ibiaku Ntok Okpo Primary Health Centre"]},
    {"lga": "Ikot Abasi", "facilities": ["ak Base Ikot Abasi Primary Health Centre", "ak Ikot Akan Primary Health Centre"]},
    {"lga": "Ikot Ekpene", "facilities": ["ak Ikot Ekpene Primary Health Centre", "ak General Hospital, Ikot Ekpene"]},
    {"lga": "Ini", "facilities": ["ak Mbia Obong Ikot Udofia Primary Health Centre", "ak Odoro Ikpe Primary Health Centre (Operational Base)"]},
    {"lga": "Itu", "facilities": ["Primary Health Care Operational Base, Mbak-Itam", "ak West Itam Primary Health Centre"]},
    {"lga": "Mbo", "facilities": ["ak Ibaka Primary Health Centre", "ak Enwang Primary Health Centre"]},
    {"lga": "Mkpat Enin", "facilities": ["ak Ikot Akpaden Health Centre", "ak Mkpat Enin Primary Health Centre"]},
    {"lga": "Nsit Atai", "facilities": ["Primary Health Care Operational Base, Odot", "ak Ikot Uyo Primary Health Centre"]},
    {"lga": "Nsit Ibom", "facilities": ["ak Mbiokporo Model Health Care Centre", "ak Afaha Offiong Primary Health Care Operational Base"]},
    {"lga": "Nsit Ubium", "facilities": ["ak Phc Operational Base, Ikot Edibon", "Akai Ubium Cottage Hospital"]},
    {"lga": "Obot Akara", "facilities": ["ak Nto Edino Primary Health Centre"]},
    {"lga": "Okobo", "facilities": ["ak Okopedi Primary Health Centre", "ak General Hospital, Ammamong"]},
    {"lga": "Onna", "facilities": ["ak Base Abat Primary Health Centre"]},
    {"lga": "Oron", "facilities": ["ak Oron Operational Base Primary Health Centre", "Iquita  General Hospital"]},
    {"lga": "Oruk Anam", "facilities": ["Ikot Akpan Essien Health Centre", "ak Ikot Ibritam Primary Health Centre Operational Base", "Ekparakwa Health Centre"]},
    {"lga": "Udung Uko", "facilities": ["ak Eyo Okponung Primary Health Centre"]},
    {"lga": "Ukanafun", "facilities": ["ak Ikot Akpa Nkuk Primary Health Centre", "Utu Nsekhe Health Centre"]},
    {"lga": "Uruan", "facilities": ["ak Idu-Uruan Primary Health Centre"]},
    {"lga": "Urue Offong/Oruko", "facilities": ["ak Oruko Primary Health Centre", "ak Primary Health Centre, Urue Offong", "ak Edok-Oruko Health Centre"]},
    {"lga": "Uyo", "facilities": ["ak Primary Health Center Ikot Okubo", "ak St Luke''s Hospital, Anua", "ak PHC Ewet Offot"]}
]}'::json),
('Anambra', '{"lgas": [
    {"lga": "Aguata", "facilities": ["AGUATA PHC", "AWALASI UGA HEALTH POST", "PHC OYE ACHINA"]},
    {"lga": "Anambra East", "facilities": ["OGBU PHC", "IGBARIAM OLD PHC"]},
    {"lga": "Anambra West", "facilities": ["UMUONUORA PHC", "REFERAL HEALTH CENTER OROMA-ETITI", "UMUEZE-ANAM PHC 1"]},
    {"lga": "Anaocha", "facilities": ["PHC OBELEDU", "CRRHC NENI", "PHC ADAZI-ENU 1"]},
    {"lga": "Awka North", "facilities": ["PHC MGBAKWU", "ACHALLA PHC"]},
    {"lga": "Awka South", "facilities": ["MCH AMAWBIA", "PHC NIBO"]},
    {"lga": "Ayamelum", "facilities": ["AMIKWE PHC OMOR", "AMIKWE PHC OMOR 1", "AMIKWE PHC OMOR 2", "AMIKWE PHC OMOR 3", "IFITE-OGWARI PHC", "AMAISUDALA PHC", "AMAH PHC"]},
    {"lga": "Dunukofia", "facilities": ["PHC UKPOMILI", "PHC UKWULU"]},
    {"lga": "Ekwusigo", "facilities": ["ICHI REF PHC", "OZUBULU REF PHC"]},
    {"lga": "Idemili North", "facilities": ["IBOLO HEALTH POST OBOSI 1", "IBOLO HEALTH POST OBOSI 2", "MCH OGIDI", "MPHC OBOSI 1"]},
    {"lga": "Idemili South", "facilities": ["PHC OBA", "OBA 1 PHC", "PHC OJOTO", "PHC AWKAETITI 2"]},
    {"lga": "Ihiala", "facilities": ["AZIA PHC", "UMUATUEGWU PHC", "MBOSI PHC"]},
    {"lga": "Njikoka", "facilities": ["MCH ABAGANA", "PHC ABAGANA"]},
    {"lga": "Nnewi North", "facilities": ["PHC OKPUNO OTOLO", "PHC EME-COURT", "PHC OBIURUAGU"]},
    {"lga": "Nnewi South", "facilities": ["OSUMENYI PHC", "EKWULUMILI PHC", "EZIAMA PHC"]},
    {"lga": "Ogbaru", "facilities": ["OKPOKO 1 PHC", "OKPOKO 2 PHC", "OKPOKO 3 PHC"]},
    {"lga": "Onitsha North", "facilities": ["ST MARKS PHC", "BASIC HEALTH CENTER ONITSHA"]},
    {"lga": "Onitsha South", "facilities": ["ST JOHNS ANGLICAN HEALTH CENTER", "MODEL PHC ODUAKPU", "MODEL PHC UMUNNA"]},
    {"lga": "Orumba North", "facilities": ["MPHC AJALLI", "PHC AMAOKPALA", "PHC AWA"]},
    {"lga": "Orumba South", "facilities": ["CHC LOMU", "PHC EZIRA", "PHC ISULO"]},
    {"lga": "Oyi", "facilities": ["OGBUNIKE PHC", "NTEJE 4 PHC", "IFITE AWKUZU PHC"]}
]}'::json),
('Cross River', '{"lgas": [
    {"lga": "Abi", "facilities": ["Ebom Primary Health Center", "Bazchure Health Center", "Ngarabe Primary Health Center"]},
    {"lga": "Akamkpa", "facilities": ["Ekong Health Center", "Ayaeba Primary Health Center", "Njangachang Primary Health Center"]},
    {"lga": "Akpabuyo", "facilities": ["Ikot Okon Idem Health Center", "Ikot Offiong Ambai Primary Health Center", "Akwa Obio Iwang Primary Health Center"]},
    {"lga": "Bakassi", "facilities": ["Ikang Primary Health Center", "Abakpa Health Center", "Ikot Effiom Health Post"]},
    {"lga": "Bekwarra", "facilities": ["Agiga Health Post", "Anikang-Iye Health Post", "Ikaparikobo Ishane Health Post"]},
    {"lga": "Biase", "facilities": ["Abini Primary Health Center", "Ikot Okpora Primary Health Center"]},
    {"lga": "Boki", "facilities": ["PHC Bashua", "MPHC Nsadop", "PHC Ntamante"]},
    {"lga": "Calabar Municipal", "facilities": ["Ikot Nkebre Health Center", "Nasarawa Health Center", "Akai Effa Health Center"]},
    {"lga": "Etung", "facilities": ["Mfum Health Post", "PHC Etomi", "Health Post Ekimaya"]},
    {"lga": "Ikom", "facilities": ["Health Post Nkaransi I", "Primary Health Center Agbaragba", "Health Center Nde Afi"]},
    {"lga": "Obanliku", "facilities": ["PHC Utanga", "Bebuekayang Health Post", "PHC Utuhu"]},
    {"lga": "Obubra", "facilities": ["Ofumbongha Health Centre", "Edondon Health Centre", "Ofoduhsa Primary Health Centre"]},
    {"lga": "Odukpani", "facilities": ["Akim-Akim Health Post", "Ikot Obong Eno Health Facility", "Ikot Effiong Otop CHC"]},
    {"lga": "Ogoja", "facilities": ["Ukende Health Post", "Nwang Health Centre", "Egbe Health Post"]},
    {"lga": "Yakurr", "facilities": ["Patapata Health Center", "Ntankpo Health Center", "Ajere Beach Health Center"]},
    {"lga": "Yala", "facilities": ["AyekoHealth Post", "Yabu Health Post", "Ijiraga Health center"]}
]}'::json),
('Enugu', '{"lgas": [
    {"lga": "Aninri", "facilities": ["Mpu Comprehensive Health Centre", "Model Health Centre Agboechara"]},
    {"lga": "Awgu", "facilities": ["Ezere HF", "Mgbidi HF"]},
    {"lga": "Enugu East", "facilities": ["Nkwubor HC", "Ugbo-Owa HC", "Ugboezeji HC", "Edem Nike HC"]},
    {"lga": "Enugu North", "facilities": ["Coal Camp HC", "Artizan Health Post", "Umunevo Health Post", "Carter HC"]},
    {"lga": "Enugu South", "facilities": ["Amechi HC", "Achara 2 HC", "IKIRIKE HC", "Obeagu HC"]},
    {"lga": "Ezeagu", "facilities": ["Agba Umana HC", "Iwollo HF", "Okpogho HF", "Olo HC"]},
    {"lga": "Igbo-Etiti", "facilities": ["Useh Health Post Aku", "Ama Ekwefu Health Post", "Ohemje HC"]},
    {"lga": "Igbo-Eze North", "facilities": ["Okata HC", "Ikpamodo HF", "Umuopu HC", "Ette HC"]},
    {"lga": "Igbo-Eze South", "facilities": ["Iheakpu Ulo HC", "Ajuona Ovoko HC", "Nkalagu Obukpa HC", "Uluanya HC"]},
    {"lga": "Isi-Uzo", "facilities": ["Abor HC", "Eha Amufu HC"]},
    {"lga": "Nkanu East", "facilities": ["Mbuluowo HC", "Algon HC", "Enuogu HC"]},
    {"lga": "Nkanu West", "facilities": ["Obe HC", "0''eji Ndiagu Akpugo HC", "Amurri HC", "Obeaghu HC"]},
    {"lga": "Nsukka", "facilities": ["Basic Health Center Lejja", "Akaibute Health Center", "Edem Ani Health Center", "Alor Uno Health Center", "Edeoballa Health Center"]},
    {"lga": "Oji River", "facilities": ["Okwe Central HC", "Agbalaenyi HC", "Umuaga Inyi health centre", "Agbadala Health centre"]},
    {"lga": "Udenu", "facilities": ["Ogbodu Aba HC", "Igugu HC", "Nkwo Orba Algon CHC", "Obollo Eke Early Bird HC"]},
    {"lga": "Udi", "facilities": ["Ngwo Uno HC", "Nsude HC"]},
    {"lga": "Uzo-Uwani", "facilities": ["Adani Health center", "Ogurugu Health center", "Igga Health center", "Ojjor Health center"]}
]}'::json);

